Account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('logged/', views.logged, name='logged'),
    path('signedup/', views.signedup, name='signedup'),
    path('login/', views.login_views, name='login'),
    path('signup/', views.signup_views, name='signup'),
    path('logout/', views.logout_views, name='logout')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('store/', include('store.urls')),
    path('account/', include('Account.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('<int:num>', views.details, name='details'),
    path('author/<str:auth>', views.author, name='author'),
]

web/urls.py
from django.urls import path
from . import views


app_name = 'web'
urlpatterns = [
    path('', views.index, name='index'),
    path('explore/', views.explore, name='explore'),
    path('<str:col>', views.explore, name='collection'),
    path('create/', views.create, name='create'),
    path('category/<str:cat>', views.items, name='category'),
    path('search/', views.search_post, name='search'),
]

Account/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from django.contrib.auth.models import User
from web.models import Category, Collection


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    Artist = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    Bid_now = models.CharField(max_length=100)
    Bid_future = models.CharField(max_length=100)
    token_id = models.CharField(max_length=255)
    date = models.DateField(auto_now_add=True)
    image = models.ImageField(upload_to='store/', null=True)
    Active = models.BooleanField(default=False)
    category = models.ManyToManyField(Category)
    collection = models.ManyToManyField(Collection)
    image_details = models.ImageField(upload_to='store/details/', null=True)

    def __str__(self):
        return self.title


class Author(models.Model):

    Adult = 'adult'
    TeenAger = 'teenager'
    Child = 'child'

    Age_fields = (
        (Adult, 'adult'),
        (TeenAger, 'teenager'),
        (Child, 'child'))

    name = models.CharField(max_length=255)
    Family = models.CharField(max_length=255)
    Age = models.IntegerField()
    National_ID = models.IntegerField()
    Followers = models.IntegerField()
    income = models.FloatField()
    username = models.ManyToManyField(User)
    posts = models.ManyToManyField(Post)
    age_category = models.CharField(
        max_length=255, choices=Age_fields, default=Adult)

    def __str__(self):
        self.fullname = self.name + " " + self.Family
        return self.fullname


class BidDetail(models.Model):
    customer_bid = models.CharField(max_length=255)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.customer_bid

web/models.py
from django.db import models

# Create your models here.


class Create(models.Model):
    title = models.CharField(max_length=255)
    discription = models.CharField(max_length=255)
    email = models.EmailField()
    price = models.FloatField()
    benefit = models.CharField(max_length=255)
    upload = models.FileField(upload_to='uploads/%Y/%m/%d/')
    Active = models.BooleanField(default=False)
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'توکن'
        verbose_name_plural = 'توکن ها'
        ordering = ['-created_time']


class Category(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='store/Category')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'categories'


class Collection(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='collection/', null=True)
    hot = models.BooleanField(default=False)
    category = models.ManyToManyField(Category)

    def __str__(self):
        return self.name

store/forms.py
from django import forms
from .models import BidDetail, Post


class BidForm(forms.ModelForm):
    class Meta:
        model = BidDetail
        fields = ['customer_bid']

web/forms.py
from email import message
from django import forms
from .models import Create


class CreateToken(forms.ModelForm):
    class Meta:
        model = Create
        fields = ['title', 'discription',
                  'email', 'price', 'benefit', 'upload']

Account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.


def login_views(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('/account/logged/')

    forms = AuthenticationForm()
    return render(request, 'account/login.html', {'forms': forms})


def logged(request):
    return render(request, 'account/redirect.html')


def signup_views(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            forms = UserCreationForm(request.POST)
            if forms.is_valid():
                forms.save()
                return redirect('/account/signedup/')

    forms = UserCreationForm()
    return render(request, 'account/signup.html')


def signedup(request):
    return render(request, 'account/redirect-signup.html')


@login_required
def logout_views(request):
    logout(request)
    return render(request, 'account/redirect-logout.html')

store/views.py
from django.shortcuts import render, redirect
from .models import Post, Author, BidDetail
from .forms import BidForm


def details(request, num):
    post = Post.objects.get(pk=num)
    if request.method == 'POST':
        forms = BidForm(request.POST)
        if forms.is_valid():
            forms.save()
            return redirect('/')
    forms = BidForm()
    return render(request, 'store/details.html', {'post': post, 'forms': forms})


def author(request, auth):
    profile = Author.objects.get(username__username=auth)
    posts = Post.objects.filter(Active=1, Artist__username=auth)
    context = {'profile': profile, 'posts': posts}
    return render(request, 'store/author.html', context)

web/views.py
from django.shortcuts import render, redirect
from store.models import Post
from .models import Category, Collection, Create
from .forms import CreateToken


def index(request):
    posts = Post.objects.filter(Active=1)
    context = {'posts': posts}
    return render(request, 'web/index.html', context)


def explore(request, col=None):
    posts = Post.objects.filter(Active=1)
    if col != None:
        posts = posts.filter(collection__name=col)

    context = {'posts': posts}
    return render(request, 'web/explore.html', context)


def create(request):
    if request.method == 'POST':
        forms = CreateToken(request.POST, request.FILES)
        print(forms)
        if forms.is_valid():
            forms.save()
            return redirect('/')

    forms = CreateToken()
    return render(request, 'web/create.html', {'forms': forms})


def items(request, cat):
    posts = Post.objects.filter(Active=1, category__name=cat)
    category = Category.objects.get(name=cat)
    context = {'posts': posts, 'category': category}

    return render(request, 'web/items.html', context)


def search_post(request):
    if request.method == 'GET':
        search = request.GET.get('s')
        posts = Post.objects.filter(content__contains=search)

    context = {'posts': posts}
    return render(request, 'web/explore.html', context)

templates/store/author.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
        <!-- header area start -->
        <header class="header-area header-sticky">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <nav class="main-nav">
                            <!-- logo start -->
                            <a href="index.html" class="logo">
                                <img src="{% static 'assets/images/logo.png' %}" alt>
                            </a>
                            <!-- logo end -->

                            <!-- menu start -->
                            <ul class="nav">
                                <li><a href="{% url 'web:index' %}">صفحه اصلی</a></li>
                                <li><a href="{% url 'web:explore' %}">جستجو</a></li>
                                <li><a href="{% url 'web:create' %}">ساخت توکن</a></li>
                                <li><a href="{% url 'account:login' %}">ورود/ثبت نام</a></li>
                            </ul>
                            <a class='menu-trigger'>
                                <span>Menu</span>
                            </a>
                            <!-- menu end -->
                        </nav>
                    </div>
                </div>
            </div>
        </header>
        <!-- header area end -->

        <div class="page-heading normal-space">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <h6>مشخصات نویسنده</h6>
                        <h2>عنوان</h2>
                        <span>خانه > <a href="#">نویسنده</a></span>
                        <div class="button">
                            <div class="main-button">
                                <a href="explore.html">آیتم های ما را جستجو کنید</a>
                            </div>
                            <div class="border-button">
                                <a href="create.html">ساخت توکن</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="author-page">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="author">
                            <img src="{% static 'assets/images/single-author.jpg' %}" alt
                                style="border-radius: 50%; max-width: 170px;">
                            <h4>{{profile.Family}} {{profile.name}}<br> <a href="#">{{profile.username.get}}</a></h4>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="right-info">
                            <div class="row">
                                <div class="col-4">
                                    <div class="info-item">
                                        <i class="fa fa-hand"></i>
                                        <h6>{{profile.Followers}}<em>فالور</em></h6>
                                    </div>
                                </div>
                                <div class="col-4">
                                    <div class="info-item">
                                        <i class="fa fa-dollar"></i>
                                        <h6>{{profile.income}}<em>درآمد</em></h6>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5">
                                    <h5>{{profile.Followers}}فالور</h5>
                                </div>
                                <div class="col-7">
                                    <div class="main-button">
                                        <a href="#">{{profile.username.get}} را دنبال کنید</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="section-heading">
                            <div class="line-dec"></div>
                            <h2><em>آیتم های </em>{{profile.name}} {{profile.Family}}</h2>
                        </div>
                    </div>
                    {% for post in posts %}
                    <div class="col-lg-3 col-md-6">
                        <div class="item">
                            <div class="row">
                                <div class="col-lg-12">
                                    <span class="author">
                                        <img src="{% static 'assets/images/author.jpg' %}" alt
                                            style="max-width: 50px; border-radius: 50%;">
                                    </span>
                                    <img src="{{post.image.url}}" alt
                                        style="border-radius: 20px;">
                                    <h4>{{post.title}}</h4>
                                </div>
                                <div class="col-lg-12">
                                    <div class="line-dec"></div>
                                    <div class="row">
                                        <div class="col-6">
                                            <span>پیشنهاد فعلی : <br><strong>{{post.Bid_now}}</strong></span>
                                        </div>
                                        <div class="col-6">
                                            <span>به پایان می رسد: <br><strong>{{post.date}}</strong></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="main-button">
                                        <a href="{% url 'store:details' num=post.pk %}">مشاهده</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="create-nft">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="section-heading">
                            <div class="line-dec"></div>
                            <h2>NFT خودت رو بساز و داخل مارکت قرار بده</h2>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="main-button">
                            <a href="create.html">الان توکن خود رو بساز</a>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="item first-item">
                            <div class="number">
                                <h6>1</h6>
                            </div>
                            <div class="icon">
                                <img src="{% static 'assets/images/icon-02.png' %}" alt>
                            </div>
                            <h4>کیف پول خود را ایجاد کنید</h4>
                            <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از
                                صنعت چاپ و با استفاده از طراحان گرافیک است
                                چاپگرها و متون بلکه روزنامه و مجله در ستون و
                                سطرآنچنان که لازم است</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="item second-item">
                            <div class="number">
                                <h6>2</h6>
                            </div>
                            <div class="icon">
                                <img src="{% static 'assets/images/icon-04.png' %}" alt>
                            </div>
                            <h4>NFT دیجیتال خود را اضافه کنید</h4>
                            <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از
                                صنعت چاپ و با استفاده از طراحان گرافیک است
                                چاپگرها و متون بلکه روزنامه و مجله در ستون و
                                سطرآنچنان که لازم است </p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="item">
                            <div class="icon">
                                <img src="{% static 'assets/images/icon-06.png' %}" alt>
                            </div>
                            <h4>NFT خود را بفروشید کسب سود کنید</h4>
                            <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از
                                صنعت چاپ و با استفاده از طراحان گرافیک است
                                چاپگرها و متون بلکه روزنامه و مجله در ستون و
                                سطرآنچنان که لازم است </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% endblock %}

templates/store/details.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<!-- header area start -->
<header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- Logo start -->
                    <a href="index.html" class="logo"><img
                            src="{% static 'assets/images/logo.png' %}" alt></a>
                    <!-- logo end -->
                    <!-- menu start -->
                    <ul class="nav">
                        <li><a href="{% url 'web:index' %}">صفحه اصلی</a></li>
                        <li><a href="{% url 'web:explore' %}">جستجو</a></li>
                        <li><a href="{% url 'web:create' %}">ساخت توکن</a></li>
                        <li><a href="{% url 'account:login' %}">ورود/ثبت نام</a></li>
                    </ul>
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- Menu end -->
                </nav>
            </div>
        </div>
    </div>
</header>
<!-- header area end -->

<div class="page-heading normal-space">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h6>فروشگاه Liberty</h6>
                <h2>عنوان</h2>
                <span>خانه<a href="#">جزئیات آیتم</a></span>
                <div class="button">
                    <div class="main-button">
                        <a href="{% url 'web:explore' %}">جستجو آیتم ها</a>
                    </div>
                    <div class="border-button">
                        <a href="{% url 'web:create' %}">ساخت توکن</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="item-details-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-heading">
                    <div class="line-dec"></div>
                    <h2>نمایش جزئیات <em>برای آیتم</em></h2>
                </div>
            </div>
            <div class="col-lg-7">
                <div class="left-image">
                    <img src="{{post.image_details.url}}" alt
                        style="border-radius: 20px;">
                </div>
            </div>
            <div class="col-lg-5 align-self-center">
                <h4>{{post.title}}</h4>
                <span class="author">
                    <img src="{% static 'assets/images/author-02.jpg'%}" alt
                        style="max-width: 50px; border-radius: 50%;">
                    <h6>هنرمند<br><a
                            href="{% url 'store:author' auth=post.Artist %}">{{post.Artist}}</a></h6>
                </span>
                <p>{{post.content}}</p>
                <div class="row">
                    <div class="col-3">
                        <span class="bid">
                            پیشنهاد فعلی <br><strong>{{post.Bid_now}}</strong><br><em>{{post.Bid_future}}</em>
                        </span>
                    </div>
                    <div class="col-4">
                        <span class="owner">
                            مالک<br><strong>{{post.Artist.get_full_name}}</strong><br><em>{{post.Artist}}</em>
                        </span>
                    </div>
                    <div class="col-5">
                        <span class="ends">
                            به پایان می رسد<br><strong>{{post.token_id}}</strong><br><em>{{post.date}}</em>
                        </span>
                    </div>
                </div>
                <form id="BidDetail"
                    action="{% url 'store:details' num=post.pk %}" method="post">
                    {% csrf_token %}
                    <label for="quantity-text">پیشنهاد شما:</label>
                    <input name="customer_bid" type="text" id="customer_bid"
                        placeholder="1 ETH" class="quantity-text" required>
                    <button type="submit" id="form-submit"
                        class="main-button">همین حالا ثبت کن</button>
                </form>
            </div>
            <div class="col-lg-12">
                <div class="current-bid">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="mini-heading">
                                <h4>عنوان</h4>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <fieldset>
                                <select name="Category"
                                    id="chooseCategory"
                                    class="form-select"
                                    aria-label="Default select example"
                                    onchange="this.form.click()">
                                    <option selected>مرتب سازی بر
                                        اساس:آخرین</option>
                                    <option type="checkbox"
                                        name="option1" value="old">مرتب
                                        سازی بر اساس: قدیمی ترین</option>
                                    <option value="low">مرتب سازی بر
                                        اساس : کمترین</option>
                                    <option value="high">مرتب سازی بر
                                        اساس : بالاترین</option>
                                </select>
                            </fieldset>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="item">
                                <div class="left-img">
                                    <img
                                        src="{% static 'assets/images/current-01.jpg' %}"
                                        alt>
                                </div>
                                <div class="right-content">
                                    <h4>هنرمند</h4>
                                    <a href="#">@username</a>
                                    <div class="line-dec"></div>
                                    <h6>پیشنهاد: <em>250,000 تومان </em></h6>
                                    <span class="date">24/07/1401, 22:00</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="item">
                                <div class="left-img">
                                    <img
                                        src="{% static 'assets/images/current-02.jpg' %}"
                                        alt>
                                </div>
                                <div class="right-content">
                                    <h4>هنرمند</h4>
                                    <a href="#">@username</a>
                                    <div class="line-dec"></div>
                                    <h6>پیشنهاد: <em>250,000 تومان </em></h6>
                                    <span class="date">24/07/1401, 22:00</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="item">
                                <div class="left-img">
                                    <img
                                        src="{% static 'assets/images/current-03.jpg' %}"
                                        alt>
                                </div>
                                <div class="right-content">
                                    <h4>هنرمند</h4>
                                    <a href="#">@username</a>
                                    <div class="line-dec"></div>
                                    <h6>پیشنهاد: <em>250,000 تومان </em></h6>
                                    <span class="date">24/07/1401, 22:00</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="item">
                                <div class="left-img">
                                    <img
                                        src="{% static 'assets/images/current-02.jpg' %}"
                                        alt>
                                </div>
                                <div class="right-content">
                                    <h4>هنرمند</h4>
                                    <a href="#">@username</a>
                                    <div class="line-dec"></div>
                                    <h6>پیشنهاد: <em>250,000 تومان </em></h6>
                                    <span class="date">24/07/1401, 22:00</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="item">
                                <div class="left-img">
                                    <img
                                        src="{% static 'assets/images/current-04.jpg' %}"
                                        alt>
                                </div>
                                <div class="right-content">
                                    <h4>هنرمند</h4>
                                    <a href="#">@username</a>
                                    <div class="line-dec"></div>
                                    <h6>پیشنهاد: <em>250,000 تومان </em></h6>
                                    <span class="date">24/07/1401, 22:00</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="item">
                                <div class="left-img">
                                    <img
                                        src="{% static 'assets/images/current-01.jpg' %}"
                                        alt>
                                </div>
                                <div class="right-content">
                                    <h4>هنرمند</h4>
                                    <a href="#">@username</a>
                                    <div class="line-dec"></div>
                                    <h6>پیشنهاد: <em>250,000 تومان </em></h6>
                                    <span class="date">24/07/1401, 22:00</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- create nft -->
<div class="create-nft">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="section-heading">
                    <div class="line-dec"></div>
                    <h2>NFT خودت رو بساز و داخل مارکت قرار بده</h2>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="main-button">
                    <a href="{% url 'web:create' %}">الان توکن خود رو بساز</a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="item first-item">
                    <div class="number">
                        <h6>1</h6>
                    </div>
                    <div class="icon">
                        <img src="{% static 'assets/images/icon-02.png' %}" alt>
                    </div>
                    <h4>کیف پول خود را ایجاد کنید</h4>
                    <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از
                        صنعت چاپ و با استفاده از طراحان گرافیک است
                        چاپگرها و متون بلکه روزنامه و مجله در ستون و
                        سطرآنچنان که لازم است</p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="item second-item">
                    <div class="number">
                        <h6>2</h6>
                    </div>
                    <div class="icon">
                        <img src="{% static 'assets/images/icon-04.png' %}" alt>
                    </div>
                    <h4>NFT دیجیتال خود را اضافه کنید</h4>
                    <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از
                        صنعت چاپ و با استفاده از طراحان گرافیک است
                        چاپگرها و متون بلکه روزنامه و مجله در ستون و
                        سطرآنچنان که لازم است </p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="item">
                    <div class="icon">
                        <img src="{% static 'assets/images/icon-06.png' %}" alt>
                    </div>
                    <h4>NFT خود را بفروشید کسب سود کنید</h4>
                    <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از
                        صنعت چاپ و با استفاده از طراحان گرافیک است
                        چاپگرها و متون بلکه روزنامه و مجله در ستون و
                        سطرآنچنان که لازم است </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}